version: '3'

services:
  database:
    image: 'postgres:latest'
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: default_database
    volumes:
      - ${PWD}/db-data/:/var/lib/postgresql/data/

  web:
    image: nginx
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "8090:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80

  web-hello:
    image: andresnunes/hello:0.1
    ports:
      - "8091:8080"